name: Dev Charter
on:
  schedule:
    - cron: "23 3 * * 1"  # Every Monday at 03:23 UTC
  workflow_dispatch:

jobs:
  check:
    name: Check
    uses: y-marui/dev-charter/.github/workflows/check-charter.yml@main
    with:
      fail_if_outdated: true
    permissions:
      contents: write
      pull-requests: write
