name: Dev Charter

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "17 10 * * 3"  # Every Wed 10:17 UTC
  workflow_dispatch:

jobs:
  check:
    name: Check
    if: github.actor != 'dependabot[bot]'
    uses: y-marui/dev-charter/.github/workflows/check-charter.yml@main
    permissions:
      contents: write
      pull-requests: write
      actions: read
